name: CI

on: [pull_request, push]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - 2.7
          - 2.6
        gemfile:
          - gemfiles/prawn_2_4.gemfile
          - gemfiles/prawn_2_3.gemfile
          - gemfiles/prawn_2_2.gemfile
          - gemfiles/prawn_2_1.gemfile
        exclude:
          - ruby: '3.0'
            gemfile: gemfiles/prawn_2_3.gemfile
          - ruby: '3.0'
            gemfile: gemfiles/prawn_2_2.gemfile
          - ruby: '3.0'
            gemfile: gemfiles/prawn_2_1.gemfile
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Test
        run: bundle exec rake spec